
server:
  port: 8084
spring:
  application:
    name: schedule
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://192.168.43.245:8081/eureka

feign:
  client:
    config:
      default:
        loggerLevel: full

global-security-config:
  allow-url-list:
    - "/login"
    - "2/**"
    - "/swagger-resources/**"
    - "/swagger-resources"
    - "/swagger-ui**"
    - "/webjars/**"
    - "/download/**"
    - "/message/**"

jwt:
  # 密钥
  secret: tangliyi123fddsafasgkahgjdhgkjfhago9gjoasjglkkdsanglkjnfadlkgjnlfkangl;afdngafdng;
  # 过期时间 604800
  expiration: 604800
