
server:
  port: 8080
spring:
  application:
    name: zuul
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://121.196.40.164:8081/eureka

feign:
  client:
    config:
      default:
        loggerLevel: full


zuul:
  routes:
    api-schedule-url:
      path: /w/**
      serviceId: schedule
    api-model-url:
      path: /model/**
      serviceId: model-service
