
server:
  port: 8080
spring:
  application:
    name: zuul
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://121.196.40.164:8081/eureka

feign:
  client:
    config:
      default:
        loggerLevel: full

ribbon:
  ReadTimeout: 120000  #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间


zuul:
  routes:
    api-wjw-url:
      path: /w/**
      strip-prefix: true
      serviceId: client-wjw
    api-tly-url:
      path: /t/**
      strip-prefix: true
      serviceId: client-tly
    api-py-url:
      path: /p/**
      strip-prefix: true
      serviceId: client-py
    api-wx-url:
      path: /wx/**
      strip-prefix: true
      serviceId: wx
