server:
  port: 8085



appid: wx2394d34401acc0f5
secret: f3e04419e163753a4c04ac52242a4b44
url: https://api.weixin.qq.com/sns/jscode2session


jwt:
  # 密钥
  secret: tangliyi123fddsafasgkahgjdhgkjfhago9gjoasjglkkdsanglkjnfadlkgjnlfkangl;afdngafdng;
  # 过期时间 604800
  expiration: 604800

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    # 多久发一次心跳
    lease-renewal-interval-in-seconds: 5
    # 最后一次心跳后多久才能被移除
    lease-expiration-duration-in-seconds: 10

  client:
    service-url:
      defaultZone: http://121.196.40.164:8081/eureka
    # 间隔多久去拉去服务器注册信息
    # registry-fetch-interval-seconds:

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

feign:
  client:
    config:
      default:
        loggerLevel: full
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: wx